name: Publish PDF

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygments

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: notes.tex
          latexmk_shell_escape: true

      - name: Deploy PDF
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "notes.pdf"
          destination_repo: "toduko/toduko.github.io"
          destination_folder: "languages-automata-and-computability"
          destination_branch: "master"
          user_email: "teddyepich@gmail.com"
          user_name: "toduko"
